//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadEFConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageEndpointMappingDB
    {
        public int id { get; set; }
        public int UnicastBusConfigDBId { get; set; }
        public string AssemblyName { get; set; }
        public string Endpoint { get; set; }
        public string Messages { get; set; }
        public string Namespace { get; set; }
        public string TypeFullName { get; set; }
    
        public virtual UnicastBusConfigDB UnicastBusConfigDB { get; set; }
    }
}
